require("skhattane.config")
require("skhattane.remap")
require("skhattane.lazy")
require("skhattane.telescope")
require("skhattane.lsp")
require("skhattane.autocompletion")
require("skhattane.undotree")
